### ISSUE TITLE
Blob vs global.Blob

### ISSUE THREAD

**Issue by Kinka** [socketio/engine.io-parser#94]
I'm a little confused at line 106 of lib/browser.js:
```
  if (global.ArrayBuffer && data instanceof ArrayBuffer) {
    return encodeArrayBuffer(packet, supportsBinary, callback);
**  } else if (Blob && data instanceof global.Blob) { **
    return encodeBlob(packet, supportsBinary, callback);
  }
```
The **Blob** comes as a local variable from `require('blob')` while global.Blob is not. Is that on purpose?

**Comment by darrachequesne** [comment]
I think the `if (Blob)` checks whether Blob is supported ([source](https://github.com/webmodules/blob/blob/v0.0.4/index.js#L89)), so that the `new Blob` call [here](https://github.com/socketio/engine.io-parser/blob/2.1.1/lib/browser.js#L178) can be performed. Do you think of a particular use-case where that would fail ?

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.
